import { Inter } from "next/font/google";
import { DM_Sans } from "next/font/google";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { EmailJSContactProvider } from "@/ContextAPI/EmailJSContextAPIContact.jsx";

const inter = Inter({ subsets: ["latin"] });

const DM_Sans_init = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-dmsans",
});

const Space_Grotesk_init = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-spacegrotesk",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <EmailJSContactProvider>
        <body
          className={`${DM_Sans_init.variable} ${Space_Grotesk_init.variable}`}
        >
          {children}
        </body>
      </EmailJSContactProvider>
    </html>
  );
}
